import type { FastifyInstance } from 'fastify';
import type { ZodTypeProvider } from 'fastify-type-provider-zod';
import { z } from 'zod';
import { isCns } from '@cadencia/kernel';
import { rota } from '../guard';

const CnsSchema = z.string().regex(/^\d{15}$/).refine(isCns, 'CNS inválido');
const PublicRoleSchema = z.enum([
  'gestor_municipal','gestor_unidade','regulacao','acs','enfermagem','medico','dentista','auditor',
]);
const PrioridadeSchema = z.enum(['normal','prioritaria','urgente']);
const StatusEncaminhamentoSchema = z.enum(['solicitado','em_regulacao','agendado','atendido','devolvido','cancelado']);
const EquipeSchema = z.object({ id:z.string().uuid(),ine:z.string().nullable(),nome:z.string(),tipo:z.string().nullable(),ativo:z.boolean() });
const EncaminhamentoSchema = z.object({
  id:z.string().uuid(), patientId:z.string().uuid(), pacienteNome:z.string(),
  originClinicId:z.string().uuid(), destinationClinicId:z.string().uuid().nullable(),
  especialidade:z.string(), sigtapCode:z.string().nullable(), prioridade:PrioridadeSchema,
  status:StatusEncaminhamentoSchema, motivo:z.string(), resumoClinico:z.string().nullable(),
  regulacaoObservacao:z.string().nullable(), createdAt:z.string(), updatedAt:z.string(),
});

export async function susRoutes(app: FastifyInstance): Promise<void> {
  const r=app.withTypeProvider<ZodTypeProvider>();

  r.get('/v1/sus/contexto',{schema:{response:{200:z.object({
    ente:z.object({id:z.string().uuid(),nome:z.string(),municipioIbge:z.string().nullable(),uf:z.string().nullable(),tipo:z.string()}),
    unidade:z.object({id:z.string().uuid(),nome:z.string(),cnes:z.string().nullable(),municipioIbge:z.string().nullable(),tipoEstabelecimento:z.string().nullable(),codigoLocal:z.string().nullable(),timezone:z.string()}),
    perfilPublico:PublicRoleSchema.nullable(),
  })}}},rota('clinic.read',async(tx,ctx)=>{
    const {rows}=await tx.query<{
      tenant_id:string;ente_nome:string;municipio_ibge:string|null;uf:string|null;tipo_ente:string;
      clinic_id:string;unidade_nome:string;cnes:string|null;clinic_municipio_ibge:string|null;
      tipo_estabelecimento:string|null;codigo_unidade_local:string|null;timezone:string;
    }>(`SELECT t.id tenant_id,t.razao_social ente_nome,t.municipio_ibge,t.uf,t.tipo_ente,
              c.id clinic_id,c.nome unidade_nome,c.cnes,c.municipio_ibge clinic_municipio_ibge,
              c.tipo_estabelecimento,c.codigo_unidade_local,c.timezone
         FROM app.tenant t JOIN app.clinic c ON c.tenant_id=t.id
        WHERE t.id=app.current_tenant_id() AND c.id=$1`,[ctx.actor.clinicId]);
    const x=rows[0];if(!x)throw Object.assign(new Error('unidade_nao_encontrada'),{statusCode:404,dominio:'unidade_nao_encontrada'});
    const perfil=await tx.query<{public_role:z.infer<typeof PublicRoleSchema>}>(`SELECT public_role FROM app.public_membership_profile WHERE clinic_id=$1 AND user_id=$2 AND ativo`,[ctx.actor.clinicId,ctx.actor.userId]);
    return{ente:{id:x.tenant_id,nome:x.ente_nome,municipioIbge:x.municipio_ibge,uf:x.uf,tipo:x.tipo_ente},unidade:{id:x.clinic_id,nome:x.unidade_nome,cnes:x.cnes,municipioIbge:x.clinic_municipio_ibge,tipoEstabelecimento:x.tipo_estabelecimento,codigoLocal:x.codigo_unidade_local,timezone:x.timezone},perfilPublico:perfil.rows[0]?.public_role??null};
  }));

  r.patch('/v1/sus/contexto',{schema:{body:z.object({municipioIbge:z.string().regex(/^\d{7}$/).optional(),uf:z.string().regex(/^[A-Z]{2}$/).optional(),tipoEnte:z.enum(['municipio','consorcio','estado','distrito_federal','outro']).optional(),cnes:z.string().regex(/^\d{7}$/).nullable().optional(),tipoEstabelecimento:z.string().max(120).nullable().optional(),codigoLocal:z.string().max(80).nullable().optional()}).refine((v)=>Object.keys(v).length>0,'nenhum campo informado'),response:{200:z.object({atualizado:z.literal(true)})}}},rota('clinic.write',async(tx,ctx,req)=>{
    const b=req.body as {municipioIbge?:string;uf?:string;tipoEnte?:string;cnes?:string|null;tipoEstabelecimento?:string|null;codigoLocal?:string|null};
    await tx.query(`UPDATE app.tenant SET municipio_ibge=COALESCE($1,municipio_ibge),uf=COALESCE($2,uf),tipo_ente=COALESCE($3,tipo_ente) WHERE id=app.current_tenant_id()`,[b.municipioIbge??null,b.uf??null,b.tipoEnte??null]);
    await tx.query(`UPDATE app.clinic SET municipio_ibge=COALESCE($2,municipio_ibge),cnes=CASE WHEN $3::boolean THEN $4 ELSE cnes END,tipo_estabelecimento=CASE WHEN $5::boolean THEN $6 ELSE tipo_estabelecimento END,codigo_unidade_local=CASE WHEN $7::boolean THEN $8 ELSE codigo_unidade_local END WHERE id=$1`,[ctx.actor.clinicId,b.municipioIbge??null,Object.prototype.hasOwnProperty.call(b,'cnes'),b.cnes??null,Object.prototype.hasOwnProperty.call(b,'tipoEstabelecimento'),b.tipoEstabelecimento??null,Object.prototype.hasOwnProperty.call(b,'codigoLocal'),b.codigoLocal??null]);
    return{atualizado:true as const};
  }));

  r.get('/v1/sus/equipes',{schema:{response:{200:z.object({itens:z.array(EquipeSchema)})}}},rota('clinic.read',async(tx,ctx)=>{const{rows}=await tx.query<{id:string;ine:string|null;nome:string;tipo:string|null;ativo:boolean}>(`SELECT id,ine,nome,tipo,ativo FROM app.sus_team WHERE clinic_id=$1 ORDER BY ativo DESC,nome`,[ctx.actor.clinicId]);return{itens:rows};}));
  r.post('/v1/sus/equipes',{schema:{body:z.object({nome:z.string().min(2).max(160),ine:z.string().regex(/^\d{10}$/).optional(),tipo:z.string().max(80).optional()}),response:{201:EquipeSchema}}},rota('tenant.write',async(tx,ctx,req,reply)=>{const b=req.body as {nome:string;ine?:string;tipo?:string};const{rows}=await tx.query<{id:string;ine:string|null;nome:string;tipo:string|null;ativo:boolean}>(`INSERT INTO app.sus_team(clinic_id,nome,ine,tipo) VALUES($1,$2,$3,$4) RETURNING id,ine,nome,tipo,ativo`,[ctx.actor.clinicId,b.nome,b.ine??null,b.tipo??null]);void reply.code(201);return rows[0]!;}));

  r.put('/v1/sus/perfis/:userId',{schema:{params:z.object({userId:z.string().uuid()}),body:z.object({papel:PublicRoleSchema,ativo:z.boolean().optional()}),response:{200:z.object({userId:z.string().uuid(),papel:PublicRoleSchema,ativo:z.boolean()})}}},rota('tenant.write',async(tx,ctx,req)=>{const p=req.params as {userId:string};const b=req.body as {papel:z.infer<typeof PublicRoleSchema>;ativo?:boolean};const membro=await tx.query(`SELECT 1 FROM app.membership WHERE clinic_id=$1 AND user_id=$2 AND revoked_at IS NULL LIMIT 1`,[ctx.actor.clinicId,p.userId]);if(membro.rowCount===0)throw Object.assign(new Error('usuario_sem_vinculo'),{statusCode:422,dominio:'usuario_sem_vinculo'});const{rows}=await tx.query<{user_id:string;public_role:z.infer<typeof PublicRoleSchema>;ativo:boolean}>(`INSERT INTO app.public_membership_profile(clinic_id,user_id,public_role,ativo) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,clinic_id,user_id) DO UPDATE SET public_role=EXCLUDED.public_role,ativo=EXCLUDED.ativo,updated_at=clock_timestamp() RETURNING user_id,public_role,ativo`,[ctx.actor.clinicId,p.userId,b.papel,b.ativo??true]);return{userId:rows[0]!.user_id,papel:rows[0]!.public_role,ativo:rows[0]!.ativo};}));

  r.get('/v1/sus/profissionais',{schema:{response:{200:z.object({itens:z.array(z.object({professionalId:z.string().uuid(),nome:z.string(),conselho:z.string(),registroConselho:z.string(),cns:z.string().nullable(),cbo:z.string().nullable(),teamId:z.string().uuid().nullable(),ativoSus:z.boolean().nullable()}))})}}},rota('clinic.read',async(tx,ctx)=>{const{rows}=await tx.query<{professional_id:string;nome:string;conselho:string;registro_conselho:string;cns:string|null;cbo:string|null;team_id:string|null;ativo_sus:boolean|null}>(`SELECT p.id professional_id,u.full_name nome,p.conselho_profissional conselho,p.numero_conselho registro_conselho,s.cns,s.cbo,s.team_id,s.ativo ativo_sus FROM app.professional p JOIN id."user" u ON u.id=p.user_id JOIN app.membership m ON m.tenant_id=p.tenant_id AND m.user_id=p.user_id AND m.clinic_id=$1 AND m.revoked_at IS NULL LEFT JOIN LATERAL(SELECT cns,cbo,team_id,ativo FROM app.professional_sus_link x WHERE x.tenant_id=p.tenant_id AND x.clinic_id=$1 AND x.professional_id=p.id AND x.ativo ORDER BY x.valid_from DESC LIMIT 1)s ON true WHERE p.inactivated_at IS NULL ORDER BY u.full_name`,[ctx.actor.clinicId]);return{itens:rows.map((x)=>({professionalId:x.professional_id,nome:x.nome,conselho:x.conselho,registroConselho:x.registro_conselho,cns:x.cns,cbo:x.cbo,teamId:x.team_id,ativoSus:x.ativo_sus}))};}));
  r.put('/v1/sus/profissionais/:id/vinculo',{schema:{params:z.object({id:z.string().uuid()}),body:z.object({cns:CnsSchema,cbo:z.string().regex(/^\d{4,6}$/),teamId:z.string().uuid().nullable().optional(),cargaHorariaSemanal:z.number().int().min(1).max(80).nullable().optional(),ativo:z.boolean().optional()}),response:{200:z.object({professionalId:z.string().uuid(),cns:z.string(),cbo:z.string()})}}},rota('tenant.write',async(tx,ctx,req)=>{const p=req.params as{id:string};const b=req.body as{cns:string;cbo:string;teamId?:string|null;cargaHorariaSemanal?:number|null;ativo?:boolean};await tx.query(`INSERT INTO app.professional_sus_link(clinic_id,professional_id,cns,cbo,team_id,carga_horaria_semanal,ativo) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,clinic_id,professional_id,cbo) DO UPDATE SET cns=EXCLUDED.cns,team_id=EXCLUDED.team_id,carga_horaria_semanal=EXCLUDED.carga_horaria_semanal,ativo=EXCLUDED.ativo`,[ctx.actor.clinicId,p.id,b.cns,b.cbo,b.teamId??null,b.cargaHorariaSemanal??null,b.ativo??true]);return{professionalId:p.id,cns:b.cns,cbo:b.cbo};}));

  r.get('/v1/sus/cidadaos/:patientId',{schema:{params:z.object({patientId:z.string().uuid()}),response:{200:z.object({patientId:z.string().uuid(),cpf:z.string().nullable(),cns:z.string().nullable(),clinicId:z.string().uuid().nullable(),teamId:z.string().uuid().nullable(),microarea:z.string().nullable(),territorio:z.string().nullable(),prontuarioFamilia:z.string().nullable(),vulnerabilidade:z.string().nullable(),acamado:z.boolean(),domiciliado:z.boolean()}),404:z.object({erro:z.literal('nao_encontrado')})}}},rota('patient.read',async(tx,_ctx,req,reply)=>{const p=req.params as{patientId:string};const{rows}=await tx.query<{patient_id:string;cpf:string|null;cns:string|null;clinic_id:string|null;team_id:string|null;microarea:string|null;territorio:string|null;prontuario_familia:string|null;vulnerabilidade:string|null;acamado:boolean|null;domiciliado:boolean|null}>(`SELECT p.id patient_id,(SELECT value FROM clin.patient_identifier i WHERE i.patient_id=p.id AND i.kind='CPF' LIMIT 1)cpf,(SELECT value FROM clin.patient_identifier i WHERE i.patient_id=p.id AND i.kind='CNS' LIMIT 1)cns,s.clinic_id,s.team_id,s.microarea,s.territorio,s.prontuario_familia,s.vulnerabilidade,s.acamado,s.domiciliado FROM clin.patient p LEFT JOIN clin.patient_sus_profile s ON s.tenant_id=p.tenant_id AND s.patient_id=p.id WHERE p.id=$1`,[p.patientId]);const x=rows[0];if(!x)return reply.code(404).send({erro:'nao_encontrado' as const});return{patientId:x.patient_id,cpf:x.cpf,cns:x.cns,clinicId:x.clinic_id,teamId:x.team_id,microarea:x.microarea,territorio:x.territorio,prontuarioFamilia:x.prontuario_familia,vulnerabilidade:x.vulnerabilidade,acamado:x.acamado??false,domiciliado:x.domiciliado??false};}));
  r.put('/v1/sus/cidadaos/:patientId',{schema:{params:z.object({patientId:z.string().uuid()}),body:z.object({cns:CnsSchema.optional(),teamId:z.string().uuid().nullable().optional(),microarea:z.string().max(4).nullable().optional(),territorio:z.string().max(160).nullable().optional(),prontuarioFamilia:z.string().max(80).nullable().optional(),vulnerabilidade:z.enum(['baixa','media','alta','muito_alta']).nullable().optional(),acamado:z.boolean().optional(),domiciliado:z.boolean().optional()}),response:{200:z.object({patientId:z.string().uuid(),atualizado:z.literal(true)})}}},rota('patient.write',async(tx,ctx,req)=>{const p=req.params as{patientId:string};const b=req.body as{cns?:string;teamId?:string|null;microarea?:string|null;territorio?:string|null;prontuarioFamilia?:string|null;vulnerabilidade?:string|null;acamado?:boolean;domiciliado?:boolean};if(b.cns!==undefined){const conflito=await tx.query(`SELECT patient_id FROM clin.patient_identifier WHERE kind='CNS' AND value=$1 AND patient_id<>$2 LIMIT 1`,[b.cns,p.patientId]);if((conflito.rowCount??0)>0)throw Object.assign(new Error('cns_ja_vinculado'),{statusCode:409,dominio:'cns_ja_vinculado'});await tx.query(`DELETE FROM clin.patient_identifier WHERE patient_id=$1 AND kind='CNS'`,[p.patientId]);await tx.query(`INSERT INTO clin.patient_identifier(id,patient_id,kind,value) VALUES(gen_random_uuid(),$1,'CNS',$2)`,[p.patientId,b.cns]);}await tx.query(`INSERT INTO clin.patient_sus_profile(patient_id,clinic_id,team_id,microarea,territorio,prontuario_familia,vulnerabilidade,acamado,domiciliado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,patient_id) DO UPDATE SET clinic_id=EXCLUDED.clinic_id,team_id=EXCLUDED.team_id,microarea=EXCLUDED.microarea,territorio=EXCLUDED.territorio,prontuario_familia=EXCLUDED.prontuario_familia,vulnerabilidade=EXCLUDED.vulnerabilidade,acamado=EXCLUDED.acamado,domiciliado=EXCLUDED.domiciliado,updated_at=clock_timestamp()`,[p.patientId,ctx.actor.clinicId,b.teamId??null,b.microarea??null,b.territorio??null,b.prontuarioFamilia??null,b.vulnerabilidade??null,b.acamado??false,b.domiciliado??false]);return{patientId:p.patientId,atualizado:true as const};}));

  r.get('/v1/regulacao/encaminhamentos',{schema:{querystring:z.object({status:StatusEncaminhamentoSchema.optional(),limit:z.coerce.number().int().min(1).max(200).optional()}),response:{200:z.object({itens:z.array(EncaminhamentoSchema)})}}},rota('appointment.read',async(tx,_ctx,req)=>{const q=req.query as{status?:z.infer<typeof StatusEncaminhamentoSchema>;limit?:number};const{rows}=await tx.query<{id:string;patient_id:string;paciente_nome:string;origin_clinic_id:string;destination_clinic_id:string|null;especialidade:string;sigtap_code:string|null;prioridade:z.infer<typeof PrioridadeSchema>;status:z.infer<typeof StatusEncaminhamentoSchema>;motivo:string;resumo_clinico:string|null;regulacao_observacao:string|null;created_at:Date;updated_at:Date}>(`SELECT e.id,e.patient_id,coalesce(p.nome_social,p.full_name) paciente_nome,e.origin_clinic_id,e.destination_clinic_id,e.especialidade,e.sigtap_code,e.prioridade,e.status,e.motivo,e.resumo_clinico,e.regulacao_observacao,e.created_at,e.updated_at FROM app.referral e JOIN clin.patient p ON p.tenant_id=e.tenant_id AND p.id=e.patient_id WHERE($1::text IS NULL OR e.status=$1) ORDER BY CASE e.prioridade WHEN 'urgente' THEN 0 WHEN 'prioritaria' THEN 1 ELSE 2 END,e.created_at ASC LIMIT $2`,[q.status??null,q.limit??100]);return{itens:rows.map((x)=>({id:x.id,patientId:x.patient_id,pacienteNome:x.paciente_nome,originClinicId:x.origin_clinic_id,destinationClinicId:x.destination_clinic_id,especialidade:x.especialidade,sigtapCode:x.sigtap_code,prioridade:x.prioridade,status:x.status,motivo:x.motivo,resumoClinico:x.resumo_clinico,regulacaoObservacao:x.regulacao_observacao,createdAt:x.created_at.toISOString(),updatedAt:x.updated_at.toISOString()}))};}));
  r.post('/v1/regulacao/encaminhamentos',{schema:{body:z.object({patientId:z.string().uuid(),destinationClinicId:z.string().uuid().nullable().optional(),especialidade:z.string().min(2).max(160),sigtapCode:z.string().regex(/^\d{10}$/).optional(),prioridade:PrioridadeSchema.optional(),motivo:z.string().min(3).max(4000),resumoClinico:z.string().max(12000).optional()}),response:{201:z.object({id:z.string().uuid(),status:StatusEncaminhamentoSchema})}}},rota('appointment.write',async(tx,ctx,req,reply)=>{const b=req.body as{patientId:string;destinationClinicId?:string|null;especialidade:string;sigtapCode?:string;prioridade?:z.infer<typeof PrioridadeSchema>;motivo:string;resumoClinico?:string};const{rows}=await tx.query<{id:string;status:z.infer<typeof StatusEncaminhamentoSchema>}>(`INSERT INTO app.referral(patient_id,origin_clinic_id,destination_clinic_id,requested_by_user_id,especialidade,sigtap_code,prioridade,motivo,resumo_clinico) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,status`,[b.patientId,ctx.actor.clinicId,b.destinationClinicId??null,ctx.actor.userId,b.especialidade,b.sigtapCode??null,b.prioridade??'normal',b.motivo,b.resumoClinico??null]);void reply.code(201);return rows[0]!;}));
  r.patch('/v1/regulacao/encaminhamentos/:id',{schema:{params:z.object({id:z.string().uuid()}),body:z.object({status:StatusEncaminhamentoSchema,destinationClinicId:z.string().uuid().nullable().optional(),observacao:z.string().max(4000).nullable().optional()}),response:{200:z.object({id:z.string().uuid(),status:StatusEncaminhamentoSchema})}}},rota('appointment.write',async(tx,_ctx,req)=>{const p=req.params as{id:string};const b=req.body as{status:z.infer<typeof StatusEncaminhamentoSchema>;destinationClinicId?:string|null;observacao?:string|null};const{rows}=await tx.query<{id:string;status:z.infer<typeof StatusEncaminhamentoSchema>}>(`UPDATE app.referral SET status=$2,destination_clinic_id=CASE WHEN $3::boolean THEN $4 ELSE destination_clinic_id END,regulacao_observacao=CASE WHEN $5::boolean THEN $6 ELSE regulacao_observacao END,updated_at=clock_timestamp() WHERE id=$1 RETURNING id,status`,[p.id,b.status,Object.prototype.hasOwnProperty.call(b,'destinationClinicId'),b.destinationClinicId??null,Object.prototype.hasOwnProperty.call(b,'observacao'),b.observacao??null]);if(!rows[0])throw Object.assign(new Error('encaminhamento_nao_encontrado'),{statusCode:404,dominio:'encaminhamento_nao_encontrado'});return rows[0];}));
}
